### PR TITLE
Bump Perl versions to fix various CVE's in perl 5.3[468]

### PR DESCRIPTION
**Pull request by waterkip**
See:
5.34.2: https://www.nntp.perl.org/group/perl.perl5.porters/2023/11/msg267352.html

5.36.2:https://www.nntp.perl.org/group/perl.perl5.porters/2023/11/msg267353.html

5.38.1: https://www.nntp.perl.org/group/perl.perl5.porters/2023/11/msg267354.html

### CODE REVIEW

**Review by zakame — CHANGES_REQUESTED** [review]
Will need updated SHA256s per http://nntp.perl.org/group/perl.perl5.porters/267365

**Comment by waterkip** [comment]
It seems we go to: 5.34.3, 5.36.3 and 5.38.2.

See https://www.nntp.perl.org/group/perl.perl5.porters/2023/11/msg267372.html

**Comment by waterkip** [comment]
We have the updated SHA's and version numbers from https://www.nntp.perl.org/group/perl.perl5.porters/2023/11/msg267400.html but we cannot download them yet from cpan.org:

```
Downloading https://www.cpan.org/src/5.0/perl-5.34.3.tar.xz
tar: downloads/perl-5.34.3.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Couldn't create a temp git repo for 5.34.3 at ./generate.pl line 140.
```

**Comment by zakame** [comment]
Thanks for the updates @waterkip! We can drop the `eol` renames - only the oldest previous release is moved there (e.g. 5.32.1,) and this directory is really used only for forced rebuilds like in #101

**Review by zakame — APPROVED** [review]
LGTM, will drop `eol` changes in next commit

**Pull request merged**
