### PR TITLE
generate.pl: Support building for multiple Debian releases

### LINKED ISSUE #66: Switch Perl 5.30 to Buster?
Now that buildpack-deps:stable have moved to Buster, shall we switch to Buster in Perl 5.30?

### PR DESCRIPTION
**Pull request by zakame**
This adds generating Dockerfiles for each Perl version on multiple
Debian releases, such as for the current 5.30.x to support both Debian
10 (buster) and 9 (stretch).  We also change the directory structure to
better indicate which Debian release it provides for.

Fixes #66 (after generating new Dockerfiles)

### CODE REVIEW

**Comment by Tekki** [comment]
Looks good, builds all the buster and stretch folders if I set 5.30 to
```
debian_releases:
  - buster
  - stretch
```
Shouldn't the default release in line 146 be set to 'buster'?

**Comment by zakame** [comment]
>Shouldn't the default release in line 146 be set to 'buster'?

Good catch, thanks!  This will also need updating the configs for older unsupported Perls to specify `stretch` explicitly (save for those already on `jessie`.)

**Comment by Tekki** [comment]
One more thing: If I delete all 5.030* folders and run the script then no '5.030.000-main' (without Debian release name) is built. What will the `perl:5.30` tag on Dockerhub contain, stretch or buster?

**Comment by zakame** [comment]
`perl:5.30` will default to `buster`.  I'll post a PR on https://github.com/docker-library/official-images/blob/master/library/perl after regenerating Dockerfiles and adjust the tags.

**Comment by zakame** [comment]
Sorry for the delay, I'm seeing a failure on building `perl:5.28-buster`:

```
#   Failed test 'Trapped error when attempting to write to knobbled GDBM_File'
#   at t/fatal.t line 37.
#          got: '1'
#     expected: undef

#   Failed test 'expected error message from GDBM_File'
#   at t/fatal.t line 46.
#                   ''
#     doesn't match '(?^: at .*\bfatal\.t line \d+\.\n\z)'
# Looks like you failed 2 tests of 8.
../ext/GDBM_File/t/fatal.t ......................................... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/8 subtests 
```

Have yet to recheck `perl:5.26-buster`, but this seems like https://rt.perl.org/Public/Bug/Display.html?id=133295.  Might need a Devel::PatchPerl update/PR for this to patch in https://github.com/Perl/perl5/commit/0d9e812de5885109532ec8bf484f165213ab97cb

**Comment by zakame** [comment]
https://metacpan.org/pod/Devel::PatchPerl#CAVEAT

>Devel::PatchPerl is intended only to facilitate the building of perls, not to facilitate the testing of perls. This means that it will not patch failing tests in the perl testsuite.

So for this case, likely just need to copy in https://github.com/Perl/perl5/commit/0d9e812de5885109532ec8bf484f165213ab97cb manually under the 5.2{6,8} directories.

**Comment by zakame** [comment]
I was hoping to get #68 done first, but local testing of all the new Dockerfiles for 5.26 through 5.30 seem OK for me now.  I'll merge this and make a PR for Hub publication soon.

Thanks everyone!

**Pull request merged**
